{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "28a4d93e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🔄 Đang khởi tạo mô hình InsightFace...\n",
      "Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}\n",
      "find model: C:\\Users\\PC/.insightface\\models\\buffalo_sc\\det_500m.onnx detection [1, 3, '?', '?'] 127.5 128.0\n",
      "Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}\n",
      "find model: C:\\Users\\PC/.insightface\\models\\buffalo_sc\\w600k_mbf.onnx recognition ['None', 3, 112, 112] 127.5 127.5\n",
      "set det-size: (640, 640)\n",
      "✅ Đã tải Database với 1 sinh viên.\n",
      "🚀 Đang mở Webcam... Bấm phím 'q' trên cửa sổ video để thoát.\n",
      "❌ Không thể kết nối Webcam!\n",
      "👋 Đã đóng Webcam an toàn.\n"
     ]
    }
   ],
   "source": [
    "import cv2\n",
    "import pickle\n",
    "import numpy as np\n",
    "import insightface\n",
    "from insightface.app import FaceAnalysis\n",
    "\n",
    "print(\"🔄 Đang khởi tạo mô hình InsightFace...\")\n",
    "app = FaceAnalysis(name='buffalo_sc', providers=['CPUExecutionProvider'])\n",
    "app.prepare(ctx_id=0, det_size=(640, 640))\n",
    "\n",
    "# Đọc Database vector\n",
    "try:\n",
    "    with open(\"database.pkl\", \"rb\") as f:\n",
    "        known_embeddings = pickle.load(f)\n",
    "    print(f\"✅ Đã tải Database với {len(known_embeddings)} sinh viên.\")\n",
    "except Exception as e:\n",
    "    print(f\"❌ Lỗi không đọc được database.pkl: {e}\")\n",
    "    exit()\n",
    "\n",
    "def cosine_similarity(v1, v2):\n",
    "    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))\n",
    "\n",
    "THRESHOLD = 0.3  # Đã hạ xuống 0.3 để dễ nhận diện\n",
    "cap = cv2.VideoCapture(0)\n",
    "\n",
    "print(\"🚀 Đang mở Webcam... Bấm phím 'q' trên cửa sổ video để thoát.\")\n",
    "\n",
    "frame_count = 0\n",
    "SKIP_FRAMES = 3 \n",
    "cached_faces = [] \n",
    "\n",
    "while cap.isOpened():\n",
    "    ret, frame = cap.read()\n",
    "    if not ret:\n",
    "        print(\"❌ Không thể kết nối Webcam!\")\n",
    "        break\n",
    "\n",
    "    frame_count += 1\n",
    "    if frame_count % SKIP_FRAMES == 0:\n",
    "        cached_faces = app.get(frame)\n",
    "\n",
    "    for face in cached_faces:\n",
    "        bbox = face.bbox.astype(int)\n",
    "        x1, y1, x2, y2 = bbox[0], bbox[1], bbox[2], bbox[3]\n",
    "        current_embedding = face.normed_embedding\n",
    "\n",
    "        max_similarity = -1.0\n",
    "        identity = \"Unknown\"\n",
    "\n",
    "        for name, saved_embedding in known_embeddings.items():\n",
    "            sim = cosine_similarity(current_embedding, saved_embedding)\n",
    "            if sim > max_similarity:\n",
    "                max_similarity = sim\n",
    "                if sim >= THRESHOLD:\n",
    "                    identity = name\n",
    "\n",
    "        if identity != \"Unknown\":\n",
    "            color = (0, 255, 0) # Xanh lá\n",
    "            text = f\"{identity} ({max_similarity:.2f})\"\n",
    "        else:\n",
    "            color = (0, 0, 255) # Đỏ\n",
    "            text = f\"Unknown ({max_similarity:.2f})\"\n",
    "\n",
    "        cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)\n",
    "        cv2.putText(frame, text, (x1, y1 - 10), \n",
    "                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)\n",
    "\n",
    "    cv2.imshow(\"Face Attendance - Terminal Mode\", frame)\n",
    "\n",
    "    if cv2.waitKey(1) & 0xFF == ord('q'):\n",
    "        break\n",
    "\n",
    "cap.release()\n",
    "cv2.destroyAllWindows()\n",
    "print(\"👋 Đã đóng Webcam an toàn.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
